version: '3.8'

services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    restart: always
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stats.rule=Host(`stats.yourdomain.com`)"
      - "traefik.http.routers.stats.entrypoints=websecure"
      - "traefik.http.routers.stats.tls.certresolver=myresolver"
      - "traefik.http.services.stats.loadbalancer.server.port=19999"

networks:
  traefik_network:
    external:
      name: web
